let number=20;

console.log("value of number is :",number)
console.log(`value of number is ${number}`)

try{

console.log("b value is :",b)
}
catch (err) {
    console.error("error occured!",err.message)
}

console.log('end of code')

